"""Prompts module for LLM interactions."""
from .dynamic import (
    ALREADY_MATCHED_PROMPT,
    GENERAL_RESPONSE_PROMPT,
    MATCH_ACCEPTED_PROMPT,
    MATCH_DECISION_PROMPT,
    MATCH_DECLINED_PROMPT,
    MATCH_FOUND_PROMPT,
    MENTOR_INTRO_PROMPT,
    NEEDS_ONBOARDING_PROMPT,
    NO_MATCHES_PROMPT,
    ONBOARDING_COMPLETE_PROMPT,
    ONBOARDING_QUESTION_PROMPT,
    PROFILE_NOT_FOUND_PROMPT,
)
from .matcher import BILATERAL_SCORING_PROMPT, MATCH_PITCH_PROMPT
from .mentor import (
    CONVERSATION_CONTINUATION_PROMPT,
    ICEBREAKER_PROMPT,
    POST_DATE_DEBRIEF_PROMPT,
    PRE_DATE_PREP_PROMPT,
    RECOVERY_PROMPT,
)
from .onboarding import PROFILE_EXTRACTION_PROMPT, PROFILE_UPDATE_PROMPT
from .router import INTENT_CLASSIFICATION_PROMPT

__all__ = [
    "INTENT_CLASSIFICATION_PROMPT",
    "PROFILE_EXTRACTION_PROMPT",
    "PROFILE_UPDATE_PROMPT",
    "BILATERAL_SCORING_PROMPT",
    "MATCH_PITCH_PROMPT",
    "ICEBREAKER_PROMPT",
    "CONVERSATION_CONTINUATION_PROMPT",
    "PRE_DATE_PREP_PROMPT",
    "POST_DATE_DEBRIEF_PROMPT",
    "RECOVERY_PROMPT",
    # Dynamic response prompts
    "GENERAL_RESPONSE_PROMPT",
    "ONBOARDING_QUESTION_PROMPT",
    "ONBOARDING_COMPLETE_PROMPT",
    "MATCH_FOUND_PROMPT",
    "MATCH_DECISION_PROMPT",
    "MATCH_ACCEPTED_PROMPT",
    "MATCH_DECLINED_PROMPT",
    "NO_MATCHES_PROMPT",
    "ALREADY_MATCHED_PROMPT",
    "MENTOR_INTRO_PROMPT",
    "PROFILE_NOT_FOUND_PROMPT",
    "NEEDS_ONBOARDING_PROMPT",
]
